package org.wavelabs.soundscope.use_cases.fingerprint;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.charset.StandardCharsets;
import org.wavelabs.soundscope.use_cases.fingerprint.chromaprint.ChromaprintException;
import org.wavelabs.soundscope.use_cases.fingerprint.chromaprint.chromaprint_h;


/**
 * Wrapper of the native chromaprint shared library, extracted using jextract. Provides fingerprint
 * extraction and manages native resources.
 */
public class AudioFingerprinter implements AudioProcessor, AutoCloseable {
    private final Arena arena;
    private final MemorySegment ctx;
    private final int sampleRate;
    private final int numChannels;
    private MemorySegment fingerprintAddress;

    /**
     * Creates a new AudioFingerprinter with the standard sample rate of 44.1 kHz and 2 (stereo)
     * channels.
     */
    public AudioFingerprinter() {
        this(44100, 2);
    }

    /**
     * Creates a new AudioFingerprinter given the audio's sample rate and number of channels.
     * 
     * @param sampleRate same rate of the audio stream
     * @param numChannels numbers of channels in the audio stream (1 or 2)
     */
    public AudioFingerprinter(final int sampleRate, final int numChannels) {
        arena = Arena.ofConfined();
        ctx = chromaprint_h.chromaprint_new(chromaprint_h.CHROMAPRINT_ALGORITHM_DEFAULT());
        this.sampleRate = sampleRate;
        this.numChannels = numChannels;
    }

    /**
     * Restarts the computation of a fingerprint with a new audio stream.
     */
    @Override
    public void start() {
        final int ok = chromaprint_h.chromaprint_start(ctx, sampleRate, numChannels);
        if (ok == 0) {
            throw new ChromaprintException(
                    "Failed to (re)start the computation of fingerprint with a new audio steam.");
        }


    }

    /**
     * Feeds provided audio data into chromaprint.
     */
    @Override
    public void processChunk(final byte[] chunk, final int numBytes) {
        final int numSamples = numBytes / 2;
        final MemorySegment data = bytesToShorts(chunk, numSamples);
        chromaprint_h.chromaprint_feed(ctx, data, numSamples);
    }

    /**
     * Convert byte array into a MemorySegment representing an array of shorts
     *
     * @param chunk byte array representing audio data
     * @param numSamples number of samples that {@code chunk} contains
     * @return MemorySegment representing array of shorts with information identical to the input
     */
    private MemorySegment bytesToShorts(final byte[] chunk, final int numSamples) {
        final MemorySegment data = arena.allocate(ValueLayout.JAVA_SHORT, numSamples);
        for (int i = 0; i < numSamples; i++) {
            final short sample = (short) (chunk[i * 2 + 1] << 8 | chunk[i * 2] & 0xFF);
            data.setAtIndex(ValueLayout.JAVA_SHORT, i, sample);
        }
        return data;
    }

    /**
     * Processes any remaining buffered audio data.
     */
    @Override
    public void stop() {
        final int ok = chromaprint_h.chromaprint_finish(ctx);
        if (ok == 0) {
            throw new ChromaprintException("Failed to process remaining buffered audio data.");
        }
    }

    /**
     * Returns the calculated fingerprint generated by chromaprint as a compressed string.
     * 
     * @return fingerprint of already-fed audio data.
     */
    public String getFingerprint() {
        final MemorySegment fingerprintPtr = arena.allocate(ValueLayout.ADDRESS);
        final int ok = chromaprint_h.chromaprint_get_fingerprint(ctx, fingerprintPtr);
        if (ok == 0) {
            throw new ChromaprintException(
                    "Fingerprint extraction failed. Make sure chromaprint has been finished.");
        }
        // Dereference char** to get the fingerprint
        fingerprintAddress = fingerprintPtr.get(ValueLayout.ADDRESS, 0);
        final MemorySegment fingerprintWithSize = fingerprintAddress.reinterpret(Long.MAX_VALUE);
        return fingerprintWithSize.getString(0, StandardCharsets.UTF_8);
    }

    @Override
    public void close() {
        chromaprint_h.chromaprint_dealloc(fingerprintAddress);
        chromaprint_h.chromaprint_free(ctx);
    }
}
