// Generated by jextract, with slight modification to load libraries

package org.wavelabs.soundscope.use_cases.fingerprint.chromaprint;

import java.io.IOException;
import java.io.InputStream;
import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout.OfByte;
import java.lang.foreign.ValueLayout.OfInt;
import java.lang.foreign.ValueLayout.OfLong;
import java.lang.foreign.ValueLayout.OfShort;
import java.lang.invoke.MethodHandle;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;

public class chromaprint_h extends chromaprint_h$shared {

    chromaprint_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = loadLibrary();

    private static SymbolLookup loadLibrary() {
        try {
            String libName = System.mapLibraryName("chromaprint");
            String resourcePath = "/lib/" + libName;

            InputStream input = chromaprint_h.class.getResourceAsStream(resourcePath);
            if (input == null) {
                throw new ChromaprintException("Chromaprint library not found.");
            }
            String extension = libName.substring(libName.indexOf("."));
            Path tempLib = Files.createTempFile("chromaprint", extension);
            Files.copy(input, tempLib, StandardCopyOption.REPLACE_EXISTING);
            input.close();

            return SymbolLookup.libraryLookup(tempLib, LIBRARY_ARENA)
                    .or(SymbolLookup.loaderLookup()).or(Linker.nativeLinker().defaultLookup());
        } catch (IOException ex) {
            throw new ChromaprintException("Failed to load chromaprint.");
        }
    }

    private static final int _STDINT_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _STDINT_H 1
     * }
     */
    public static int _STDINT_H() {
        return _STDINT_H;
    }

    private static final int _FEATURES_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _FEATURES_H 1
     * }
     */
    public static int _FEATURES_H() {
        return _FEATURES_H;
    }

    private static final int _DEFAULT_SOURCE = (int) 1L;

    /**
     * {@snippet lang = c : * #define _DEFAULT_SOURCE 1
     * }
     */
    public static int _DEFAULT_SOURCE() {
        return _DEFAULT_SOURCE;
    }

    private static final int __GLIBC_USE_ISOC2Y = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_ISOC2Y 0
     * }
     */
    public static int __GLIBC_USE_ISOC2Y() {
        return __GLIBC_USE_ISOC2Y;
    }

    private static final int __GLIBC_USE_ISOC23 = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_ISOC23 0
     * }
     */
    public static int __GLIBC_USE_ISOC23() {
        return __GLIBC_USE_ISOC23;
    }

    private static final int __USE_ISOC11 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_ISOC11 1
     * }
     */
    public static int __USE_ISOC11() {
        return __USE_ISOC11;
    }

    private static final int __USE_ISOC99 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_ISOC99 1
     * }
     */
    public static int __USE_ISOC99() {
        return __USE_ISOC99;
    }

    private static final int __USE_ISOC95 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_ISOC95 1
     * }
     */
    public static int __USE_ISOC95() {
        return __USE_ISOC95;
    }

    private static final int __USE_POSIX_IMPLICITLY = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_POSIX_IMPLICITLY 1
     * }
     */
    public static int __USE_POSIX_IMPLICITLY() {
        return __USE_POSIX_IMPLICITLY;
    }

    private static final int _POSIX_SOURCE = (int) 1L;

    /**
     * {@snippet lang = c : * #define _POSIX_SOURCE 1
     * }
     */
    public static int _POSIX_SOURCE() {
        return _POSIX_SOURCE;
    }

    private static final int __USE_POSIX = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_POSIX 1
     * }
     */
    public static int __USE_POSIX() {
        return __USE_POSIX;
    }

    private static final int __USE_POSIX2 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_POSIX2 1
     * }
     */
    public static int __USE_POSIX2() {
        return __USE_POSIX2;
    }

    private static final int __USE_POSIX199309 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_POSIX199309 1
     * }
     */
    public static int __USE_POSIX199309() {
        return __USE_POSIX199309;
    }

    private static final int __USE_POSIX199506 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_POSIX199506 1
     * }
     */
    public static int __USE_POSIX199506() {
        return __USE_POSIX199506;
    }

    private static final int __USE_XOPEN2K = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_XOPEN2K 1
     * }
     */
    public static int __USE_XOPEN2K() {
        return __USE_XOPEN2K;
    }

    private static final int __USE_XOPEN2K8 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_XOPEN2K8 1
     * }
     */
    public static int __USE_XOPEN2K8() {
        return __USE_XOPEN2K8;
    }

    private static final int _ATFILE_SOURCE = (int) 1L;

    /**
     * {@snippet lang = c : * #define _ATFILE_SOURCE 1
     * }
     */
    public static int _ATFILE_SOURCE() {
        return _ATFILE_SOURCE;
    }

    private static final int __WORDSIZE = (int) 64L;

    /**
     * {@snippet lang = c : * #define __WORDSIZE 64
     * }
     */
    public static int __WORDSIZE() {
        return __WORDSIZE;
    }

    private static final int __WORDSIZE_TIME64_COMPAT32 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __WORDSIZE_TIME64_COMPAT32 1
     * }
     */
    public static int __WORDSIZE_TIME64_COMPAT32() {
        return __WORDSIZE_TIME64_COMPAT32;
    }

    private static final int __SYSCALL_WORDSIZE = (int) 64L;

    /**
     * {@snippet lang = c : * #define __SYSCALL_WORDSIZE 64
     * }
     */
    public static int __SYSCALL_WORDSIZE() {
        return __SYSCALL_WORDSIZE;
    }

    private static final int __USE_TIME_BITS64 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_TIME_BITS64 1
     * }
     */
    public static int __USE_TIME_BITS64() {
        return __USE_TIME_BITS64;
    }

    private static final int __USE_MISC = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_MISC 1
     * }
     */
    public static int __USE_MISC() {
        return __USE_MISC;
    }

    private static final int __USE_ATFILE = (int) 1L;

    /**
     * {@snippet lang = c : * #define __USE_ATFILE 1
     * }
     */
    public static int __USE_ATFILE() {
        return __USE_ATFILE;
    }

    private static final int __USE_FORTIFY_LEVEL = (int) 0L;

    /**
     * {@snippet lang = c : * #define __USE_FORTIFY_LEVEL 0
     * }
     */
    public static int __USE_FORTIFY_LEVEL() {
        return __USE_FORTIFY_LEVEL;
    }

    private static final int __GLIBC_USE_DEPRECATED_GETS = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_DEPRECATED_GETS 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_GETS() {
        return __GLIBC_USE_DEPRECATED_GETS;
    }

    private static final int __GLIBC_USE_DEPRECATED_SCANF = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_DEPRECATED_SCANF 0
     * }
     */
    public static int __GLIBC_USE_DEPRECATED_SCANF() {
        return __GLIBC_USE_DEPRECATED_SCANF;
    }

    private static final int __GLIBC_USE_C23_STRTOL = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_C23_STRTOL 0
     * }
     */
    public static int __GLIBC_USE_C23_STRTOL() {
        return __GLIBC_USE_C23_STRTOL;
    }

    private static final int _STDC_PREDEF_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _STDC_PREDEF_H 1
     * }
     */
    public static int _STDC_PREDEF_H() {
        return _STDC_PREDEF_H;
    }

    private static final int __STDC_IEC_559__ = (int) 1L;

    /**
     * {@snippet lang = c : * #define __STDC_IEC_559__ 1
     * }
     */
    public static int __STDC_IEC_559__() {
        return __STDC_IEC_559__;
    }

    private static final int __STDC_IEC_559_COMPLEX__ = (int) 1L;

    /**
     * {@snippet lang = c : * #define __STDC_IEC_559_COMPLEX__ 1
     * }
     */
    public static int __STDC_IEC_559_COMPLEX__() {
        return __STDC_IEC_559_COMPLEX__;
    }

    private static final int __GNU_LIBRARY__ = (int) 6L;

    /**
     * {@snippet lang = c : * #define __GNU_LIBRARY__ 6
     * }
     */
    public static int __GNU_LIBRARY__() {
        return __GNU_LIBRARY__;
    }

    private static final int __GLIBC__ = (int) 2L;

    /**
     * {@snippet lang = c : * #define __GLIBC__ 2
     * }
     */
    public static int __GLIBC__() {
        return __GLIBC__;
    }

    private static final int __GLIBC_MINOR__ = (int) 42L;

    /**
     * {@snippet lang = c : * #define __GLIBC_MINOR__ 42
     * }
     */
    public static int __GLIBC_MINOR__() {
        return __GLIBC_MINOR__;
    }

    private static final int _SYS_CDEFS_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _SYS_CDEFS_H 1
     * }
     */
    public static int _SYS_CDEFS_H() {
        return _SYS_CDEFS_H;
    }

    private static final int __glibc_c99_flexarr_available = (int) 1L;

    /**
     * {@snippet lang = c : * #define __glibc_c99_flexarr_available 1
     * }
     */
    public static int __glibc_c99_flexarr_available() {
        return __glibc_c99_flexarr_available;
    }

    private static final int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = (int) 0L;

    /**
     * {@snippet lang = c : * #define __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI 0
     * }
     */
    public static int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI() {
        return __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI;
    }

    private static final int __HAVE_GENERIC_SELECTION = (int) 1L;

    /**
     * {@snippet lang = c : * #define __HAVE_GENERIC_SELECTION 1
     * }
     */
    public static int __HAVE_GENERIC_SELECTION() {
        return __HAVE_GENERIC_SELECTION;
    }

    private static final int __GLIBC_USE_LIB_EXT2 = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_LIB_EXT2 0
     * }
     */
    public static int __GLIBC_USE_LIB_EXT2() {
        return __GLIBC_USE_LIB_EXT2;
    }

    private static final int __GLIBC_USE_IEC_60559_BFP_EXT = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_BFP_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT() {
        return __GLIBC_USE_IEC_60559_BFP_EXT;
    }

    private static final int __GLIBC_USE_IEC_60559_BFP_EXT_C23 = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_BFP_EXT_C23 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_BFP_EXT_C23() {
        return __GLIBC_USE_IEC_60559_BFP_EXT_C23;
    }

    private static final int __GLIBC_USE_IEC_60559_EXT = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_EXT() {
        return __GLIBC_USE_IEC_60559_EXT;
    }

    private static final int __GLIBC_USE_IEC_60559_FUNCS_EXT = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_FUNCS_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT() {
        return __GLIBC_USE_IEC_60559_FUNCS_EXT;
    }

    private static final int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23() {
        return __GLIBC_USE_IEC_60559_FUNCS_EXT_C23;
    }

    private static final int __GLIBC_USE_IEC_60559_TYPES_EXT = (int) 0L;

    /**
     * {@snippet lang = c : * #define __GLIBC_USE_IEC_60559_TYPES_EXT 0
     * }
     */
    public static int __GLIBC_USE_IEC_60559_TYPES_EXT() {
        return __GLIBC_USE_IEC_60559_TYPES_EXT;
    }

    private static final int _BITS_TYPES_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_TYPES_H 1
     * }
     */
    public static int _BITS_TYPES_H() {
        return _BITS_TYPES_H;
    }

    private static final int _BITS_TYPESIZES_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_TYPESIZES_H 1
     * }
     */
    public static int _BITS_TYPESIZES_H() {
        return _BITS_TYPESIZES_H;
    }

    private static final int __OFF_T_MATCHES_OFF64_T = (int) 1L;

    /**
     * {@snippet lang = c : * #define __OFF_T_MATCHES_OFF64_T 1
     * }
     */
    public static int __OFF_T_MATCHES_OFF64_T() {
        return __OFF_T_MATCHES_OFF64_T;
    }

    private static final int __INO_T_MATCHES_INO64_T = (int) 1L;

    /**
     * {@snippet lang = c : * #define __INO_T_MATCHES_INO64_T 1
     * }
     */
    public static int __INO_T_MATCHES_INO64_T() {
        return __INO_T_MATCHES_INO64_T;
    }

    private static final int __RLIM_T_MATCHES_RLIM64_T = (int) 1L;

    /**
     * {@snippet lang = c : * #define __RLIM_T_MATCHES_RLIM64_T 1
     * }
     */
    public static int __RLIM_T_MATCHES_RLIM64_T() {
        return __RLIM_T_MATCHES_RLIM64_T;
    }

    private static final int __STATFS_MATCHES_STATFS64 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __STATFS_MATCHES_STATFS64 1
     * }
     */
    public static int __STATFS_MATCHES_STATFS64() {
        return __STATFS_MATCHES_STATFS64;
    }

    private static final int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = (int) 1L;

    /**
     * {@snippet lang = c : * #define __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 1
     * }
     */
    public static int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64() {
        return __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64;
    }

    private static final int __FD_SETSIZE = (int) 1024L;

    /**
     * {@snippet lang = c : * #define __FD_SETSIZE 1024
     * }
     */
    public static int __FD_SETSIZE() {
        return __FD_SETSIZE;
    }

    private static final int _BITS_TIME64_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_TIME64_H 1
     * }
     */
    public static int _BITS_TIME64_H() {
        return _BITS_TIME64_H;
    }

    private static final int _BITS_WCHAR_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_WCHAR_H 1
     * }
     */
    public static int _BITS_WCHAR_H() {
        return _BITS_WCHAR_H;
    }

    private static final int _BITS_STDINT_INTN_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_STDINT_INTN_H 1
     * }
     */
    public static int _BITS_STDINT_INTN_H() {
        return _BITS_STDINT_INTN_H;
    }

    private static final int _BITS_STDINT_UINTN_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_STDINT_UINTN_H 1
     * }
     */
    public static int _BITS_STDINT_UINTN_H() {
        return _BITS_STDINT_UINTN_H;
    }

    private static final int _BITS_STDINT_LEAST_H = (int) 1L;

    /**
     * {@snippet lang = c : * #define _BITS_STDINT_LEAST_H 1
     * }
     */
    public static int _BITS_STDINT_LEAST_H() {
        return _BITS_STDINT_LEAST_H;
    }

    private static final int CHROMAPRINT_VERSION_MAJOR = (int) 1L;

    /**
     * {@snippet lang = c : * #define CHROMAPRINT_VERSION_MAJOR 1
     * }
     */
    public static int CHROMAPRINT_VERSION_MAJOR() {
        return CHROMAPRINT_VERSION_MAJOR;
    }

    private static final int CHROMAPRINT_VERSION_MINOR = (int) 6L;

    /**
     * {@snippet lang = c : * #define CHROMAPRINT_VERSION_MINOR 6
     * }
     */
    public static int CHROMAPRINT_VERSION_MINOR() {
        return CHROMAPRINT_VERSION_MINOR;
    }

    private static final int CHROMAPRINT_VERSION_PATCH = (int) 0L;

    /**
     * {@snippet lang = c : * #define CHROMAPRINT_VERSION_PATCH 0
     * }
     */
    public static int CHROMAPRINT_VERSION_PATCH() {
        return CHROMAPRINT_VERSION_PATCH;
    }

    /**
     * {@snippet lang = c : * typedef unsigned char __u_char
     * }
     */
    public static final OfByte __u_char = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef unsigned short __u_short
     * }
     */
    public static final OfShort __u_short = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef unsigned int __u_int
     * }
     */
    public static final OfInt __u_int = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef unsigned long __u_long
     * }
     */
    public static final OfLong __u_long = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef signed char __int8_t
     * }
     */
    public static final OfByte __int8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef unsigned char __uint8_t
     * }
     */
    public static final OfByte __uint8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef short __int16_t
     * }
     */
    public static final OfShort __int16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef unsigned short __uint16_t
     * }
     */
    public static final OfShort __uint16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef int __int32_t
     * }
     */
    public static final OfInt __int32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef unsigned int __uint32_t
     * }
     */
    public static final OfInt __uint32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef long __int64_t
     * }
     */
    public static final OfLong __int64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __uint64_t
     * }
     */
    public static final OfLong __uint64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __int8_t __int_least8_t
     * }
     */
    public static final OfByte __int_least8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __uint8_t __uint_least8_t
     * }
     */
    public static final OfByte __uint_least8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __int16_t __int_least16_t
     * }
     */
    public static final OfShort __int_least16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __uint16_t __uint_least16_t
     * }
     */
    public static final OfShort __uint_least16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __int32_t __int_least32_t
     * }
     */
    public static final OfInt __int_least32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __uint32_t __uint_least32_t
     * }
     */
    public static final OfInt __uint_least32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __int64_t __int_least64_t
     * }
     */
    public static final OfLong __int_least64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __uint64_t __uint_least64_t
     * }
     */
    public static final OfLong __uint_least64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __quad_t
     * }
     */
    public static final OfLong __quad_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __u_quad_t
     * }
     */
    public static final OfLong __u_quad_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __intmax_t
     * }
     */
    public static final OfLong __intmax_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __uintmax_t
     * }
     */
    public static final OfLong __uintmax_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __dev_t
     * }
     */
    public static final OfLong __dev_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned int __uid_t
     * }
     */
    public static final OfInt __uid_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef unsigned int __gid_t
     * }
     */
    public static final OfInt __gid_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef unsigned long __ino_t
     * }
     */
    public static final OfLong __ino_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __ino64_t
     * }
     */
    public static final OfLong __ino64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned int __mode_t
     * }
     */
    public static final OfInt __mode_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef unsigned long __nlink_t
     * }
     */
    public static final OfLong __nlink_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __off_t
     * }
     */
    public static final OfLong __off_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __off64_t
     * }
     */
    public static final OfLong __off64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef int __pid_t
     * }
     */
    public static final OfInt __pid_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef long __clock_t
     * }
     */
    public static final OfLong __clock_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __rlim_t
     * }
     */
    public static final OfLong __rlim_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __rlim64_t
     * }
     */
    public static final OfLong __rlim64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned int __id_t
     * }
     */
    public static final OfInt __id_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef long __time_t
     * }
     */
    public static final OfLong __time_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned int __useconds_t
     * }
     */
    public static final OfInt __useconds_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef long __suseconds_t
     * }
     */
    public static final OfLong __suseconds_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __suseconds64_t
     * }
     */
    public static final OfLong __suseconds64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef int __daddr_t
     * }
     */
    public static final OfInt __daddr_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef int __key_t
     * }
     */
    public static final OfInt __key_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef int __clockid_t
     * }
     */
    public static final OfInt __clockid_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef void *__timer_t
     * }
     */
    public static final AddressLayout __timer_t = chromaprint_h.C_POINTER;
    /**
     * {@snippet lang = c : * typedef long __blksize_t
     * }
     */
    public static final OfLong __blksize_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __blkcnt_t
     * }
     */
    public static final OfLong __blkcnt_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __blkcnt64_t
     * }
     */
    public static final OfLong __blkcnt64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __fsblkcnt_t
     * }
     */
    public static final OfLong __fsblkcnt_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __fsblkcnt64_t
     * }
     */
    public static final OfLong __fsblkcnt64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __fsfilcnt_t
     * }
     */
    public static final OfLong __fsfilcnt_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __fsfilcnt64_t
     * }
     */
    public static final OfLong __fsfilcnt64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __fsword_t
     * }
     */
    public static final OfLong __fsword_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __ssize_t
     * }
     */
    public static final OfLong __ssize_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long __syscall_slong_t
     * }
     */
    public static final OfLong __syscall_slong_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long __syscall_ulong_t
     * }
     */
    public static final OfLong __syscall_ulong_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __off64_t __loff_t
     * }
     */
    public static final OfLong __loff_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef char *__caddr_t
     * }
     */
    public static final AddressLayout __caddr_t = chromaprint_h.C_POINTER;
    /**
     * {@snippet lang = c : * typedef long __intptr_t
     * }
     */
    public static final OfLong __intptr_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned int __socklen_t
     * }
     */
    public static final OfInt __socklen_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef int __sig_atomic_t
     * }
     */
    public static final OfInt __sig_atomic_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __int8_t int8_t
     * }
     */
    public static final OfByte int8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __int16_t int16_t
     * }
     */
    public static final OfShort int16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __int32_t int32_t
     * }
     */
    public static final OfInt int32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __int64_t int64_t
     * }
     */
    public static final OfLong int64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __uint8_t uint8_t
     * }
     */
    public static final OfByte uint8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __uint16_t uint16_t
     * }
     */
    public static final OfShort uint16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __uint32_t uint32_t
     * }
     */
    public static final OfInt uint32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __uint64_t uint64_t
     * }
     */
    public static final OfLong uint64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __int_least8_t int_least8_t
     * }
     */
    public static final OfByte int_least8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __int_least16_t int_least16_t
     * }
     */
    public static final OfShort int_least16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __int_least32_t int_least32_t
     * }
     */
    public static final OfInt int_least32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __int_least64_t int_least64_t
     * }
     */
    public static final OfLong int_least64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __uint_least8_t uint_least8_t
     * }
     */
    public static final OfByte uint_least8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef __uint_least16_t uint_least16_t
     * }
     */
    public static final OfShort uint_least16_t = chromaprint_h.C_SHORT;
    /**
     * {@snippet lang = c : * typedef __uint_least32_t uint_least32_t
     * }
     */
    public static final OfInt uint_least32_t = chromaprint_h.C_INT;
    /**
     * {@snippet lang = c : * typedef __uint_least64_t uint_least64_t
     * }
     */
    public static final OfLong uint_least64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef signed char int_fast8_t
     * }
     */
    public static final OfByte int_fast8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef long int_fast16_t
     * }
     */
    public static final OfLong int_fast16_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long int_fast32_t
     * }
     */
    public static final OfLong int_fast32_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long int_fast64_t
     * }
     */
    public static final OfLong int_fast64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned char uint_fast8_t
     * }
     */
    public static final OfByte uint_fast8_t = chromaprint_h.C_CHAR;
    /**
     * {@snippet lang = c : * typedef unsigned long uint_fast16_t
     * }
     */
    public static final OfLong uint_fast16_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long uint_fast32_t
     * }
     */
    public static final OfLong uint_fast32_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long uint_fast64_t
     * }
     */
    public static final OfLong uint_fast64_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef long intptr_t
     * }
     */
    public static final OfLong intptr_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef unsigned long uintptr_t
     * }
     */
    public static final OfLong uintptr_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __intmax_t intmax_t
     * }
     */
    public static final OfLong intmax_t = chromaprint_h.C_LONG;
    /**
     * {@snippet lang = c : * typedef __uintmax_t uintmax_t
     * }
     */
    public static final OfLong uintmax_t = chromaprint_h.C_LONG;
    private static final int CHROMAPRINT_ALGORITHM_TEST1 = (int) 0L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_TEST1 = 0
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_TEST1() {
        return CHROMAPRINT_ALGORITHM_TEST1;
    }

    private static final int CHROMAPRINT_ALGORITHM_TEST2 = (int) 1L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_TEST2 = 1
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_TEST2() {
        return CHROMAPRINT_ALGORITHM_TEST2;
    }

    private static final int CHROMAPRINT_ALGORITHM_TEST3 = (int) 2L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_TEST3 = 2
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_TEST3() {
        return CHROMAPRINT_ALGORITHM_TEST3;
    }

    private static final int CHROMAPRINT_ALGORITHM_TEST4 = (int) 3L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_TEST4 = 3
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_TEST4() {
        return CHROMAPRINT_ALGORITHM_TEST4;
    }

    private static final int CHROMAPRINT_ALGORITHM_TEST5 = (int) 4L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_TEST5 = 4
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_TEST5() {
        return CHROMAPRINT_ALGORITHM_TEST5;
    }

    private static final int CHROMAPRINT_ALGORITHM_DEFAULT = (int) 1L;

    /**
     * {@snippet lang = c : * enum ChromaprintAlgorithm.CHROMAPRINT_ALGORITHM_DEFAULT = 1
     * }
     */
    public static int CHROMAPRINT_ALGORITHM_DEFAULT() {
        return CHROMAPRINT_ALGORITHM_DEFAULT;
    }

    private static class chromaprint_get_version {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * const char *chromaprint_get_version()
     * }
     */
    public static FunctionDescriptor chromaprint_get_version$descriptor() {
        return chromaprint_get_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * const char *chromaprint_get_version()
     * }
     */
    public static MethodHandle chromaprint_get_version$handle() {
        return chromaprint_get_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * const char *chromaprint_get_version()
     * }
     */
    public static MemorySegment chromaprint_get_version$address() {
        return chromaprint_get_version.ADDR;
    }

    /**
     * {@snippet lang = c : * const char *chromaprint_get_version()
     * }
     */
    public static MemorySegment chromaprint_get_version() {
        var mh$ = chromaprint_get_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_version");
            }
            return (MemorySegment) mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_new {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_new");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * ChromaprintContext *chromaprint_new(int algorithm)
     * }
     */
    public static FunctionDescriptor chromaprint_new$descriptor() {
        return chromaprint_new.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * ChromaprintContext *chromaprint_new(int algorithm)
     * }
     */
    public static MethodHandle chromaprint_new$handle() {
        return chromaprint_new.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * ChromaprintContext *chromaprint_new(int algorithm)
     * }
     */
    public static MemorySegment chromaprint_new$address() {
        return chromaprint_new.ADDR;
    }

    /**
     * {@snippet lang = c : * ChromaprintContext *chromaprint_new(int algorithm)
     * }
     */
    public static MemorySegment chromaprint_new(int algorithm) {
        var mh$ = chromaprint_new.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_new", algorithm);
            }
            return (MemorySegment) mh$.invokeExact(algorithm);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_free {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.ofVoid(chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * void chromaprint_free(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_free$descriptor() {
        return chromaprint_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * void chromaprint_free(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_free$handle() {
        return chromaprint_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * void chromaprint_free(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_free$address() {
        return chromaprint_free.ADDR;
    }

    /**
     * {@snippet lang = c : * void chromaprint_free(ChromaprintContext *ctx)
     * }
     */
    public static void chromaprint_free(MemorySegment ctx) {
        var mh$ = chromaprint_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_free", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_algorithm {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_algorithm");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_algorithm(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_algorithm$descriptor() {
        return chromaprint_get_algorithm.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_algorithm(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_algorithm$handle() {
        return chromaprint_get_algorithm.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_algorithm(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_algorithm$address() {
        return chromaprint_get_algorithm.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_algorithm(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_algorithm(MemorySegment ctx) {
        var mh$ = chromaprint_get_algorithm.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_algorithm", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_set_option {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_set_option");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_set_option(ChromaprintContext *ctx, const char *name, int value)
     * }
     */
    public static FunctionDescriptor chromaprint_set_option$descriptor() {
        return chromaprint_set_option.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_set_option(ChromaprintContext *ctx, const char *name, int value)
     * }
     */
    public static MethodHandle chromaprint_set_option$handle() {
        return chromaprint_set_option.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_set_option(ChromaprintContext *ctx, const char *name, int value)
     * }
     */
    public static MemorySegment chromaprint_set_option$address() {
        return chromaprint_set_option.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_set_option(ChromaprintContext *ctx, const char *name, int value)
     * }
     */
    public static int chromaprint_set_option(MemorySegment ctx, MemorySegment name, int value) {
        var mh$ = chromaprint_set_option.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_set_option", ctx, name, value);
            }
            return (int) mh$.invokeExact(ctx, name, value);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_num_channels {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_num_channels");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_num_channels(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_num_channels$descriptor() {
        return chromaprint_get_num_channels.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_num_channels(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_num_channels$handle() {
        return chromaprint_get_num_channels.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_num_channels(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_num_channels$address() {
        return chromaprint_get_num_channels.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_num_channels(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_num_channels(MemorySegment ctx) {
        var mh$ = chromaprint_get_num_channels.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_num_channels", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_sample_rate {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_sample_rate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_sample_rate(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_sample_rate$descriptor() {
        return chromaprint_get_sample_rate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_sample_rate(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_sample_rate$handle() {
        return chromaprint_get_sample_rate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_sample_rate(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_sample_rate$address() {
        return chromaprint_get_sample_rate.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_sample_rate(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_sample_rate(MemorySegment ctx) {
        var mh$ = chromaprint_get_sample_rate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_sample_rate", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_item_duration {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_item_duration");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_item_duration(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_item_duration$descriptor() {
        return chromaprint_get_item_duration.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_item_duration(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_item_duration$handle() {
        return chromaprint_get_item_duration.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_item_duration(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_item_duration$address() {
        return chromaprint_get_item_duration.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_item_duration(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_item_duration(MemorySegment ctx) {
        var mh$ = chromaprint_get_item_duration.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_item_duration", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_item_duration_ms {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_item_duration_ms");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_item_duration_ms(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_item_duration_ms$descriptor() {
        return chromaprint_get_item_duration_ms.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_item_duration_ms(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_item_duration_ms$handle() {
        return chromaprint_get_item_duration_ms.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_item_duration_ms(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_item_duration_ms$address() {
        return chromaprint_get_item_duration_ms.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_item_duration_ms(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_item_duration_ms(MemorySegment ctx) {
        var mh$ = chromaprint_get_item_duration_ms.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_item_duration_ms", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_delay {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_get_delay");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_delay(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_delay$descriptor() {
        return chromaprint_get_delay.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_delay(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_delay$handle() {
        return chromaprint_get_delay.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_delay(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_delay$address() {
        return chromaprint_get_delay.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_delay(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_delay(MemorySegment ctx) {
        var mh$ = chromaprint_get_delay.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_delay", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_delay_ms {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_delay_ms");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_get_delay_ms(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_get_delay_ms$descriptor() {
        return chromaprint_get_delay_ms.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_get_delay_ms(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_get_delay_ms$handle() {
        return chromaprint_get_delay_ms.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_get_delay_ms(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_get_delay_ms$address() {
        return chromaprint_get_delay_ms.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_get_delay_ms(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_get_delay_ms(MemorySegment ctx) {
        var mh$ = chromaprint_get_delay_ms.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_delay_ms", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_start {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT, chromaprint_h.C_INT);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_start");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_start(ChromaprintContext *ctx, int sample_rate, int num_channels)
     * }
     */
    public static FunctionDescriptor chromaprint_start$descriptor() {
        return chromaprint_start.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_start(ChromaprintContext *ctx, int sample_rate, int num_channels)
     * }
     */
    public static MethodHandle chromaprint_start$handle() {
        return chromaprint_start.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_start(ChromaprintContext *ctx, int sample_rate, int num_channels)
     * }
     */
    public static MemorySegment chromaprint_start$address() {
        return chromaprint_start.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_start(ChromaprintContext *ctx, int sample_rate, int num_channels)
     * }
     */
    public static int chromaprint_start(MemorySegment ctx, int sample_rate, int num_channels) {
        var mh$ = chromaprint_start.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_start", ctx, sample_rate, num_channels);
            }
            return (int) mh$.invokeExact(ctx, sample_rate, num_channels);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_feed {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_feed");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_feed(ChromaprintContext *ctx, const int16_t *data, int size)
     * }
     */
    public static FunctionDescriptor chromaprint_feed$descriptor() {
        return chromaprint_feed.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_feed(ChromaprintContext *ctx, const int16_t *data, int size)
     * }
     */
    public static MethodHandle chromaprint_feed$handle() {
        return chromaprint_feed.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_feed(ChromaprintContext *ctx, const int16_t *data, int size)
     * }
     */
    public static MemorySegment chromaprint_feed$address() {
        return chromaprint_feed.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_feed(ChromaprintContext *ctx, const int16_t *data, int size)
     * }
     */
    public static int chromaprint_feed(MemorySegment ctx, MemorySegment data, int size) {
        var mh$ = chromaprint_feed.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_feed", ctx, data, size);
            }
            return (int) mh$.invokeExact(ctx, data, size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_finish {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_finish");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_finish(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_finish$descriptor() {
        return chromaprint_finish.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_finish(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_finish$handle() {
        return chromaprint_finish.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_finish(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_finish$address() {
        return chromaprint_finish.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_finish(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_finish(MemorySegment ctx) {
        var mh$ = chromaprint_finish.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_finish", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint(ChromaprintContext *ctx, char **fingerprint)
     * }
     */
    public static FunctionDescriptor chromaprint_get_fingerprint$descriptor() {
        return chromaprint_get_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint(ChromaprintContext *ctx, char **fingerprint)
     * }
     */
    public static MethodHandle chromaprint_get_fingerprint$handle() {
        return chromaprint_get_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint(ChromaprintContext *ctx, char **fingerprint)
     * }
     */
    public static MemorySegment chromaprint_get_fingerprint$address() {
        return chromaprint_get_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint(ChromaprintContext *ctx, char **fingerprint)
     * }
     */
    public static int chromaprint_get_fingerprint(MemorySegment ctx, MemorySegment fingerprint) {
        var mh$ = chromaprint_get_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_fingerprint", ctx, fingerprint);
            }
            return (int) mh$.invokeExact(ctx, fingerprint);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_raw_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_raw_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint(ChromaprintContext *ctx, uint32_t **fingerprint, int *size)
     * }
     */
    public static FunctionDescriptor chromaprint_get_raw_fingerprint$descriptor() {
        return chromaprint_get_raw_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint(ChromaprintContext *ctx, uint32_t **fingerprint, int *size)
     * }
     */
    public static MethodHandle chromaprint_get_raw_fingerprint$handle() {
        return chromaprint_get_raw_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint(ChromaprintContext *ctx, uint32_t **fingerprint, int *size)
     * }
     */
    public static MemorySegment chromaprint_get_raw_fingerprint$address() {
        return chromaprint_get_raw_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint(ChromaprintContext *ctx, uint32_t **fingerprint, int *size)
     * }
     */
    public static int chromaprint_get_raw_fingerprint(MemorySegment ctx, MemorySegment fingerprint,
            MemorySegment size) {
        var mh$ = chromaprint_get_raw_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_raw_fingerprint", ctx, fingerprint, size);
            }
            return (int) mh$.invokeExact(ctx, fingerprint, size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_raw_fingerprint_size {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_raw_fingerprint_size");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint_size(ChromaprintContext *ctx, int *size)
     * }
     */
    public static FunctionDescriptor chromaprint_get_raw_fingerprint_size$descriptor() {
        return chromaprint_get_raw_fingerprint_size.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint_size(ChromaprintContext *ctx, int *size)
     * }
     */
    public static MethodHandle chromaprint_get_raw_fingerprint_size$handle() {
        return chromaprint_get_raw_fingerprint_size.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint_size(ChromaprintContext *ctx, int *size)
     * }
     */
    public static MemorySegment chromaprint_get_raw_fingerprint_size$address() {
        return chromaprint_get_raw_fingerprint_size.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_get_raw_fingerprint_size(ChromaprintContext *ctx, int *size)
     * }
     */
    public static int chromaprint_get_raw_fingerprint_size(MemorySegment ctx, MemorySegment size) {
        var mh$ = chromaprint_get_raw_fingerprint_size.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_raw_fingerprint_size", ctx, size);
            }
            return (int) mh$.invokeExact(ctx, size);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_get_fingerprint_hash {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_get_fingerprint_hash");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint_hash(ChromaprintContext *ctx, uint32_t *hash)
     * }
     */
    public static FunctionDescriptor chromaprint_get_fingerprint_hash$descriptor() {
        return chromaprint_get_fingerprint_hash.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint_hash(ChromaprintContext *ctx, uint32_t *hash)
     * }
     */
    public static MethodHandle chromaprint_get_fingerprint_hash$handle() {
        return chromaprint_get_fingerprint_hash.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint_hash(ChromaprintContext *ctx, uint32_t *hash)
     * }
     */
    public static MemorySegment chromaprint_get_fingerprint_hash$address() {
        return chromaprint_get_fingerprint_hash.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_get_fingerprint_hash(ChromaprintContext *ctx, uint32_t *hash)
     * }
     */
    public static int chromaprint_get_fingerprint_hash(MemorySegment ctx, MemorySegment hash) {
        var mh$ = chromaprint_get_fingerprint_hash.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_get_fingerprint_hash", ctx, hash);
            }
            return (int) mh$.invokeExact(ctx, hash);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_clear_fingerprint {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.of(chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_clear_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * int chromaprint_clear_fingerprint(ChromaprintContext *ctx)
     * }
     */
    public static FunctionDescriptor chromaprint_clear_fingerprint$descriptor() {
        return chromaprint_clear_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * int chromaprint_clear_fingerprint(ChromaprintContext *ctx)
     * }
     */
    public static MethodHandle chromaprint_clear_fingerprint$handle() {
        return chromaprint_clear_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * int chromaprint_clear_fingerprint(ChromaprintContext *ctx)
     * }
     */
    public static MemorySegment chromaprint_clear_fingerprint$address() {
        return chromaprint_clear_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c : * int chromaprint_clear_fingerprint(ChromaprintContext *ctx)
     * }
     */
    public static int chromaprint_clear_fingerprint(MemorySegment ctx) {
        var mh$ = chromaprint_clear_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_clear_fingerprint", ctx);
            }
            return (int) mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_encode_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT, chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_encode_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64)
     * }
     */
    public static FunctionDescriptor chromaprint_encode_fingerprint$descriptor() {
        return chromaprint_encode_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64)
     * }
     */
    public static MethodHandle chromaprint_encode_fingerprint$handle() {
        return chromaprint_encode_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64)
     * }
     */
    public static MemorySegment chromaprint_encode_fingerprint$address() {
        return chromaprint_encode_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_encode_fingerprint(const uint32_t *fp, int size, int algorithm, char **encoded_fp, int *encoded_size, int base64)
     * }
     */
    public static int chromaprint_encode_fingerprint(MemorySegment fp, int size, int algorithm,
            MemorySegment encoded_fp, MemorySegment encoded_size, int base64) {
        var mh$ = chromaprint_encode_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_encode_fingerprint", fp, size, algorithm, encoded_fp,
                        encoded_size, base64);
            }
            return (int) mh$.invokeExact(fp, size, algorithm, encoded_fp, encoded_size, base64);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_decode_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT, chromaprint_h.C_POINTER,
                chromaprint_h.C_POINTER, chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_decode_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint(const char *encoded_fp, int encoded_size, uint32_t **fp, int *size, int *algorithm, int base64)
     * }
     */
    public static FunctionDescriptor chromaprint_decode_fingerprint$descriptor() {
        return chromaprint_decode_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint(const char *encoded_fp, int encoded_size, uint32_t **fp, int *size, int *algorithm, int base64)
     * }
     */
    public static MethodHandle chromaprint_decode_fingerprint$handle() {
        return chromaprint_decode_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint(const char *encoded_fp, int encoded_size, uint32_t **fp, int *size, int *algorithm, int base64)
     * }
     */
    public static MemorySegment chromaprint_decode_fingerprint$address() {
        return chromaprint_decode_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint(const char *encoded_fp, int encoded_size, uint32_t **fp, int *size, int *algorithm, int base64)
     * }
     */
    public static int chromaprint_decode_fingerprint(MemorySegment encoded_fp, int encoded_size,
            MemorySegment fp, MemorySegment size, MemorySegment algorithm, int base64) {
        var mh$ = chromaprint_decode_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_decode_fingerprint", encoded_fp, encoded_size, fp, size,
                        algorithm, base64);
            }
            return (int) mh$.invokeExact(encoded_fp, encoded_size, fp, size, algorithm, base64);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_decode_fingerprint_header {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT, chromaprint_h.C_POINTER,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_decode_fingerprint_header");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint_header(const char *encoded_fp, int encoded_size, int *size, int *algorithm, int base64)
     * }
     */
    public static FunctionDescriptor chromaprint_decode_fingerprint_header$descriptor() {
        return chromaprint_decode_fingerprint_header.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint_header(const char *encoded_fp, int encoded_size, int *size, int *algorithm, int base64)
     * }
     */
    public static MethodHandle chromaprint_decode_fingerprint_header$handle() {
        return chromaprint_decode_fingerprint_header.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint_header(const char *encoded_fp, int encoded_size, int *size, int *algorithm, int base64)
     * }
     */
    public static MemorySegment chromaprint_decode_fingerprint_header$address() {
        return chromaprint_decode_fingerprint_header.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_decode_fingerprint_header(const char *encoded_fp, int encoded_size, int *size, int *algorithm, int base64)
     * }
     */
    public static int chromaprint_decode_fingerprint_header(MemorySegment encoded_fp,
            int encoded_size, MemorySegment size, MemorySegment algorithm, int base64) {
        var mh$ = chromaprint_decode_fingerprint_header.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_decode_fingerprint_header", encoded_fp, encoded_size,
                        size, algorithm, base64);
            }
            return (int) mh$.invokeExact(encoded_fp, encoded_size, size, algorithm, base64);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_hash_fingerprint {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(chromaprint_h.C_INT,
                chromaprint_h.C_POINTER, chromaprint_h.C_INT, chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR =
                SYMBOL_LOOKUP.findOrThrow("chromaprint_hash_fingerprint");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int chromaprint_hash_fingerprint(const uint32_t *fp, int size, uint32_t *hash)
     * }
     */
    public static FunctionDescriptor chromaprint_hash_fingerprint$descriptor() {
        return chromaprint_hash_fingerprint.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int chromaprint_hash_fingerprint(const uint32_t *fp, int size, uint32_t *hash)
     * }
     */
    public static MethodHandle chromaprint_hash_fingerprint$handle() {
        return chromaprint_hash_fingerprint.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int chromaprint_hash_fingerprint(const uint32_t *fp, int size, uint32_t *hash)
     * }
     */
    public static MemorySegment chromaprint_hash_fingerprint$address() {
        return chromaprint_hash_fingerprint.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int chromaprint_hash_fingerprint(const uint32_t *fp, int size, uint32_t *hash)
     * }
     */
    public static int chromaprint_hash_fingerprint(MemorySegment fp, int size, MemorySegment hash) {
        var mh$ = chromaprint_hash_fingerprint.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_hash_fingerprint", fp, size, hash);
            }
            return (int) mh$.invokeExact(fp, size, hash);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chromaprint_dealloc {
        public static final FunctionDescriptor DESC =
                FunctionDescriptor.ofVoid(chromaprint_h.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chromaprint_dealloc");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * void chromaprint_dealloc(void *ptr)
     * }
     */
    public static FunctionDescriptor chromaprint_dealloc$descriptor() {
        return chromaprint_dealloc.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * void chromaprint_dealloc(void *ptr)
     * }
     */
    public static MethodHandle chromaprint_dealloc$handle() {
        return chromaprint_dealloc.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * void chromaprint_dealloc(void *ptr)
     * }
     */
    public static MemorySegment chromaprint_dealloc$address() {
        return chromaprint_dealloc.ADDR;
    }

    /**
     * {@snippet lang = c : * void chromaprint_dealloc(void *ptr)
     * }
     */
    public static void chromaprint_dealloc(MemorySegment ptr) {
        var mh$ = chromaprint_dealloc.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chromaprint_dealloc", ptr);
            }
            mh$.invokeExact(ptr);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static final long _POSIX_C_SOURCE = 200809L;

    /**
     * {@snippet lang = c : * #define _POSIX_C_SOURCE 200809
     * }
     */
    public static long _POSIX_C_SOURCE() {
        return _POSIX_C_SOURCE;
    }

    private static final int __TIMESIZE = (int) 64L;

    /**
     * {@snippet lang = c : * #define __TIMESIZE 64
     * }
     */
    public static int __TIMESIZE() {
        return __TIMESIZE;
    }

    private static final long __STDC_IEC_60559_BFP__ = 201404L;

    /**
     * {@snippet lang = c : * #define __STDC_IEC_60559_BFP__ 201404
     * }
     */
    public static long __STDC_IEC_60559_BFP__() {
        return __STDC_IEC_60559_BFP__;
    }

    private static final long __STDC_IEC_60559_COMPLEX__ = 201404L;

    /**
     * {@snippet lang = c : * #define __STDC_IEC_60559_COMPLEX__ 201404
     * }
     */
    public static long __STDC_IEC_60559_COMPLEX__() {
        return __STDC_IEC_60559_COMPLEX__;
    }

    private static final long __STDC_ISO_10646__ = 201706L;

    /**
     * {@snippet lang = c : * #define __STDC_ISO_10646__ 201706
     * }
     */
    public static long __STDC_ISO_10646__() {
        return __STDC_ISO_10646__;
    }

    private static final int __WCHAR_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c : * #define __WCHAR_MAX 2147483647
     * }
     */
    public static int __WCHAR_MAX() {
        return __WCHAR_MAX;
    }

    private static final int __WCHAR_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c : * #define __WCHAR_MIN -2147483648
     * }
     */
    public static int __WCHAR_MIN() {
        return __WCHAR_MIN;
    }

    private static final int INT8_MIN = (int) -128L;

    /**
     * {@snippet lang = c : * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return INT8_MIN;
    }

    private static final int INT16_MIN = (int) -32768L;

    /**
     * {@snippet lang = c : * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return INT16_MIN;
    }

    private static final int INT32_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c : * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return INT32_MIN;
    }

    private static final long INT64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return INT64_MIN;
    }

    private static final int INT8_MAX = (int) 127L;

    /**
     * {@snippet lang = c : * #define INT8_MAX 127
     * }
     */
    public static int INT8_MAX() {
        return INT8_MAX;
    }

    private static final int INT16_MAX = (int) 32767L;

    /**
     * {@snippet lang = c : * #define INT16_MAX 32767
     * }
     */
    public static int INT16_MAX() {
        return INT16_MAX;
    }

    private static final int INT32_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c : * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return INT32_MAX;
    }

    private static final long INT64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return INT64_MAX;
    }

    private static final int UINT8_MAX = (int) 255L;

    /**
     * {@snippet lang = c : * #define UINT8_MAX 255
     * }
     */
    public static int UINT8_MAX() {
        return UINT8_MAX;
    }

    private static final int UINT16_MAX = (int) 65535L;

    /**
     * {@snippet lang = c : * #define UINT16_MAX 65535
     * }
     */
    public static int UINT16_MAX() {
        return UINT16_MAX;
    }

    private static final int UINT32_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c : * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return UINT32_MAX;
    }

    private static final long UINT64_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return UINT64_MAX;
    }

    private static final int INT_LEAST8_MIN = (int) -128L;

    /**
     * {@snippet lang = c : * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return INT_LEAST8_MIN;
    }

    private static final int INT_LEAST16_MIN = (int) -32768L;

    /**
     * {@snippet lang = c : * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return INT_LEAST16_MIN;
    }

    private static final int INT_LEAST32_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c : * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return INT_LEAST32_MIN;
    }

    private static final long INT_LEAST64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return INT_LEAST64_MIN;
    }

    private static final int INT_LEAST8_MAX = (int) 127L;

    /**
     * {@snippet lang = c : * #define INT_LEAST8_MAX 127
     * }
     */
    public static int INT_LEAST8_MAX() {
        return INT_LEAST8_MAX;
    }

    private static final int INT_LEAST16_MAX = (int) 32767L;

    /**
     * {@snippet lang = c : * #define INT_LEAST16_MAX 32767
     * }
     */
    public static int INT_LEAST16_MAX() {
        return INT_LEAST16_MAX;
    }

    private static final int INT_LEAST32_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c : * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return INT_LEAST32_MAX;
    }

    private static final long INT_LEAST64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return INT_LEAST64_MAX;
    }

    private static final int UINT_LEAST8_MAX = (int) 255L;

    /**
     * {@snippet lang = c : * #define UINT_LEAST8_MAX 255
     * }
     */
    public static int UINT_LEAST8_MAX() {
        return UINT_LEAST8_MAX;
    }

    private static final int UINT_LEAST16_MAX = (int) 65535L;

    /**
     * {@snippet lang = c : * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static int UINT_LEAST16_MAX() {
        return UINT_LEAST16_MAX;
    }

    private static final int UINT_LEAST32_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c : * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return UINT_LEAST32_MAX;
    }

    private static final long UINT_LEAST64_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return UINT_LEAST64_MAX;
    }

    private static final int INT_FAST8_MIN = (int) -128L;

    /**
     * {@snippet lang = c : * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return INT_FAST8_MIN;
    }

    private static final long INT_FAST16_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INT_FAST16_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST16_MIN() {
        return INT_FAST16_MIN;
    }

    private static final long INT_FAST32_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INT_FAST32_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST32_MIN() {
        return INT_FAST32_MIN;
    }

    private static final long INT_FAST64_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return INT_FAST64_MIN;
    }

    private static final int INT_FAST8_MAX = (int) 127L;

    /**
     * {@snippet lang = c : * #define INT_FAST8_MAX 127
     * }
     */
    public static int INT_FAST8_MAX() {
        return INT_FAST8_MAX;
    }

    private static final long INT_FAST16_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INT_FAST16_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST16_MAX() {
        return INT_FAST16_MAX;
    }

    private static final long INT_FAST32_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INT_FAST32_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST32_MAX() {
        return INT_FAST32_MAX;
    }

    private static final long INT_FAST64_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return INT_FAST64_MAX;
    }

    private static final int UINT_FAST8_MAX = (int) 255L;

    /**
     * {@snippet lang = c : * #define UINT_FAST8_MAX 255
     * }
     */
    public static int UINT_FAST8_MAX() {
        return UINT_FAST8_MAX;
    }

    private static final long UINT_FAST16_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINT_FAST16_MAX -1
     * }
     */
    public static long UINT_FAST16_MAX() {
        return UINT_FAST16_MAX;
    }

    private static final long UINT_FAST32_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINT_FAST32_MAX -1
     * }
     */
    public static long UINT_FAST32_MAX() {
        return UINT_FAST32_MAX;
    }

    private static final long UINT_FAST64_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return UINT_FAST64_MAX;
    }

    private static final long INTPTR_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return INTPTR_MIN;
    }

    private static final long INTPTR_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return INTPTR_MAX;
    }

    private static final long UINTPTR_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return UINTPTR_MAX;
    }

    private static final long INTMAX_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return INTMAX_MIN;
    }

    private static final long INTMAX_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return INTMAX_MAX;
    }

    private static final long UINTMAX_MAX = -1L;

    /**
     * {@snippet lang = c : * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return UINTMAX_MAX;
    }

    private static final long PTRDIFF_MIN = -9223372036854775808L;

    /**
     * {@snippet lang = c : * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return PTRDIFF_MIN;
    }

    private static final long PTRDIFF_MAX = 9223372036854775807L;

    /**
     * {@snippet lang = c : * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return PTRDIFF_MAX;
    }

    private static final int SIG_ATOMIC_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c : * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return SIG_ATOMIC_MIN;
    }

    private static final int SIG_ATOMIC_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c : * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return SIG_ATOMIC_MAX;
    }

    private static final long SIZE_MAX = -1L;

    /**
     * {@snippet lang = c : * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return SIZE_MAX;
    }

    private static final int WCHAR_MIN = (int) -2147483648L;

    /**
     * {@snippet lang = c : * #define WCHAR_MIN -2147483648
     * }
     */
    public static int WCHAR_MIN() {
        return WCHAR_MIN;
    }

    private static final int WCHAR_MAX = (int) 2147483647L;

    /**
     * {@snippet lang = c : * #define WCHAR_MAX 2147483647
     * }
     */
    public static int WCHAR_MAX() {
        return WCHAR_MAX;
    }

    private static final int WINT_MIN = (int) 0L;

    /**
     * {@snippet lang = c : * #define WINT_MIN 0
     * }
     */
    public static int WINT_MIN() {
        return WINT_MIN;
    }

    private static final int WINT_MAX = (int) 4294967295L;

    /**
     * {@snippet lang = c : * #define WINT_MAX 4294967295
     * }
     */
    public static int WINT_MAX() {
        return WINT_MAX;
    }
}

